### ISSUE TITLE
Problem with Dynamic attach

### ISSUE THREAD

**Issue by asafkiv** [Appdynamics/Dynamic-Agent-MA#2]
(Sorry about the stupid title...)
I just used it today. thanks. 
Trying to monitor my java processes, got many messages similar to:
Dynamic attach successful
Attaching to VM [1]
▒java.util.ServiceConfigurationError: com.sun.tools.attach.spi.AttachProvider: Provider sun.tools.attach.LinuxAttachProvider not found
v       at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:588)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1211)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1220)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
        at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
        at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
        at jdk.attach/com.sun.tools.attach.spi.AttachProvider.providers(AttachProvider.java:258)
        at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:200)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.singularity.ee.agent.appagent.AgentEntryPoint.main(AgentEntryPoint.java:1127)
0agent path >>>/opt/AppServerAgent/javaagent.jar
<WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.singularity.ee.agent.appagent.AgentEntryPoint (file:/opt/AppServerAgent/javaagent.jar) to method sun.tools.attach.HotSpotVirtualMachine.loadAgent(java.lang.String,java.lang.String)
WARNING: Please consider reporting this to the maintainers of com.singularity.ee.agent.appagent.AgentEntryPoint
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Any idea why? 

Thanks!
Asaf

**Comment by jdbarfield** [comment]
Is this a Java 11 process?

**Comment by asafkiv** [comment]
> Is this a Java 11 process?

java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.2+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.2+9, mixed mode)

Anything to do with it? 
Thanks.

**Comment by jdbarfield** [comment]
Yes. Java 11 is not compatible with the current version of the Dynamic Agent.

**Comment by asafkiv** [comment]
Whats a supported version than?

**Comment by jdbarfield** [comment]
Java 1.7 and Java 1.8 are supported
