### ISSUE TITLE
Exception in the machine-agent

### ISSUE THREAD

**Issue by aqiqul** [Appdynamics/Dynamic-Agent-MA#3]
Hi,
I was trying to use this on my once docker container java app.
I have not installed and configured Controller inside the tomcat container is that an issue?
The Exception I am getting from the machine-agent is
`extension-scheduler-pool-0] 13 Aug 2020 16:26:27,193 ERROR K8sContainerTags - Error retrieving tags from Kubernetes
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [Pod]  with name: [null]  in namespace: [null]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64) ~[kubernetes-client-4.8.0.jar:?]
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:72) ~[kubernetes-client-4.8.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:155) ~[kubernetes-client-4.8.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:608) ~[kubernetes-client-4.8.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:70) ~[kubernetes-client-4.8.0.jar:?]
	at com.appdynamics.agent.sim.k8s.Fabric8Client.getPodByContainerId(Fabric8Client.java:100) ~[machineagent.jar:Machine Agent v20.5.1-2635 GA compatible with 4.4.1.0 Build Date 2020-05-27 21:53:51]
	at com.appdynamics.agent.sim.k8s.Fabric8Client.getReplicaSetLabelsByContainerId(Fabric8Client.java:48) ~[machineagent.jar:Machine Agent v20.5.1-2635 GA compatible with 4.4.1.0 Build Date 2020-05-27 21:53:51]
	at com.appdynamics.agent.sim.k8s.K8sContainerTags.updateTags(K8sContainerTags.java:54) [machineagent.jar:Machine Agent v20.5.1-2635 GA compatible with 4.4.1.0 Build Date 2020-05-27 21:53:51]
	at com.appdynamics.sim.agent.extensions.servers.tags.K8sTagsSupplier.updateTags(K8sTagsSupplier.java:30) [servers-20.5.1-2635.jar:?]
	at com.appdynamics.sim.agent.extensions.servers.tags.K8sTagsScheduledRunner.run(K8sTagsScheduledRunner.java:78) [servers-20.5.1-2635.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_252]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_252]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.net.UnknownHostException: kubernetes.default.svc: Name or service not known
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[?:1.8.0_252]
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929) ~[?:1.8.0_252]
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324) ~[?:1.8.0_252]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1277) ~[?:1.8.0_252]
	at java.net.InetAddress.getAllByName(InetAddress.java:1193) ~[?:1.8.0_252]
	at java.net.InetAddress.getAllByName(InetAddress.java:1127) ~[?:1.8.0_252]
	at okhttp3.Dns$1.lookup(Dns.java:40) ~[okhttp-3.12.6.jar:?]
	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185) ~[okhttp-3.12.6.jar:?]
	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149) ~[okhttp-3.12.6.jar:?]
	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84) ~[okhttp-3.12.6.jar:?]
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:215) ~[okhttp-3.12.6.jar:?]
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135) ~[okhttp-3.12.6.jar:?]
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114) ~[okhttp-3.12.6.jar:?]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) ~[okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.12.6.jar:?]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127) ~[okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.12.6.jar:?]
	at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:134) ~[kubernetes-client-4.8.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.12.6.jar:?]
	at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68) ~[kubernetes-client-4.8.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.12.6.jar:?]
	at io.fabric8.kubernetes.client.utils.HttpClientUtils.lambda$createHttpClient$3(HttpClientUtils.java:114) ~[kubernetes-client-4.8.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.12.6.jar:?]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257) ~[okhttp-3.12.6.jar:?]
	at okhttp3.RealCall.execute(RealCall.java:93) ~[okhttp-3.12.6.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:469) ~[kubernetes-client-4.8.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:430) ~[kubernetes-client-4.8.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:412) ~[kubernetes-client-4.8.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:151) ~[kubernetes-client-4.8.0.jar:?]
	... 14 more`

Any help?

**Comment by jdbarfield** [comment]
You should probably open a support ticket. This does not look like a Dynamic Agent issue.
Thanks

**Comment by aqiqul** [comment]
Support ticket to Appdynamics?
I have not used Kubernates, just a single docker container. 
Does the Dynamic Agent support such environment.?
Thanks!

**Comment by jdbarfield** [comment]
Yes, log a support issue with AppDynamics.
And yes, the Dynamic Agent supports Kubernetes, but it must be deployed differently.
See: https://github.com/Appdynamics/Dynamic-Agent-K8
